### ISSUE TITLE
emojis not included in ss?

### ISSUE THREAD

**Issue by shreyas-jadhav** [Lete114/WebStack-Screenshot#5]

**Comment by lete114** [comment]
If you include it in your server, it will display correctly. For example, vercel itself does not have a multilingual font library, so if you install a multilingual font library in your program, vercel will exceed the size limit of your program and will not be deployed correctly.

You can customize a url font file with the font parameter https://github.com/Lete114/WebStack-Screenshot#properties

Example: `https://****/?url=xxxxx&font=https://xxxxx.ttf`

**Comment by shreyas-jadhav** [comment]
I added NotoColorEmoji font but still it doesn't show the emojis

https://webstack-screenshot.vercel.app/?url=https://testsite32.dev.ariumsites.com&fullPage=false&type=jpeg&quality=50&font=https://github.com/googlefonts/noto-emoji/blob/main/fonts/NotoColorEmoji.ttf?raw=true

**Comment by lete114** [comment]
The font request parameter is no longer needed, instead it is downloaded in advance at deployment time https://github.com/Lete114/WebStack-Screenshot#serverless
