### ISSUE TITLE
捕获页面图片质量偏低

### ISSUE THREAD

**Issue by QC2168** [Lete114/WebStack-Screenshot#7]
复现如下

访问[https://webstack-screenshot.vercel.app](https://webstack-screenshot.vercel.app/?url=https://github.com/Lete114/WebStack-Screenshot&quality=100)

页面渲染出来的图片质量偏低，例如字体出现模糊

`quality`参数已经设置为`100`

**Comment by lete114** [comment]
我觉得这清晰度很正常啊，哪模糊了？

**Comment by QC2168** [comment]
![image](https://github.com/Lete114/WebStack-Screenshot/assets/82024018/7c71ae3b-1820-4720-8643-e1706de9e090)

**Comment by lete114** [comment]
![](https://webstack-screenshot.vercel.app/?url=https://github.com/Lete114/WebStack-Screenshot&quality=100)

我觉得，还好吧。

这是 `puppeteer` 调用浏览器截的图。它相当于你自己用浏览器截图一样。

具体步骤:
1. `f12` 打开浏览器控制台
2. 按快捷键 `ctrl+shift+p` 调出浏览器命令行
3. 输入 `screenshot` 关键字
4. 选择截图的类型
![image](https://github.com/Lete114/WebStack-Screenshot/assets/48512251/4acf4a8b-d142-4218-b66d-bbdd0952257b)

**Comment by QC2168** [comment]
明白了，我看看能不能再调整
